services:

  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:1.32.0
    restart: unless-stopped
    environment:
      - DOMAIN=${VW_DOMAIN}
      - SIGNUPS_ALLOWED=false
      - ADMIN_TOKEN=${VW_ADMIN_TOKEN}
      - YUBICO_CLIENT_ID=${VW_YUBICO_CLIENT_ID}
      - YUBICO_SECRET_KEY=${VW_YUBICO_SECRET_KEY}
      - SMTP_HOST=${VW_SMTP_HOST}
      - SMTP_FROM=${VW_SMTP_FROM}
      - SMTP_USERNAME=${VW_SMTP_USERNAME}
      - SMTP_PASSWORD=${VW_SMTP_PASSWORD}
      - LOG_FILE=/data/vaultwarden.log
      - LOG_LEVEL=warn
      - EXTENDED_LOGGING=true
    volumes:
      - vaultwarden-data:/data/
    networks:
      - vaultwarden-network

  backup:
    container_name: vaultwarden-backup
    image: ttionya/vaultwarden-backup:latest
    restart: always
    environment:
      - BACKUP_KEEP_DAYS=30
      - BACKUP_FILE_SUFFIX=%Y%m%d%H%M
      - ZIP_PASSWORD=${BACKUP_ZIP_PASSWORD}
      - MAIL_SMTP_ENABLE=TRUE
      - MAIL_SMTP_VARIABLES=${BACKUP_SMTP_VARIABLES}
      - MAIL_TO=${BACKUP_MAIL_TO}
      - MAIL_WHEN_SUCCESS=FALSE
      - MAIL_WHEN_FAILURE=TRUE
    volumes:
      - vaultwarden-data:/bitwarden/data/
      - vaultwarden-rclone-data:/config/
    networks:
      - vaultwarden-network

  cloudflared:
    image: cloudflare/cloudflared:2024.5.0
    container_name: vaultwarden-cloudflared
    restart: unless-stopped
    read_only: true
    volumes:
      - ./cloudflared-config:/root/.cloudflared/
    command: [ "tunnel", "run", "${TUNNEL_ID}" ]
    user: root
    depends_on:
      - vaultwarden
    networks:
      - vaultwarden-network

volumes:
  vaultwarden-data:
    # Specify the name of the volume where you save the vaultwarden data,
    # use vaultwarden-data for new users
    # and bitwardenrs-data for migrated users
    name: vaultwarden-data
    # name: bitwardenrs-data
  vaultwarden-rclone-data:
    external: true
    # Specify the name of the volume where you save the rclone configuration,
    # use vaultwarden-rclone-data for new users
    # and bitwardenrs-rclone-data for migrated users
    name: vaultwarden-rclone-data
    # name: bitwardenrs-rclone-data

networks:
  vaultwarden-network:
    name: vaultwarden-network
    external: false