secrets:
  cf-token:
    file: ./cf-token

volumes:
  traefik-data:
    driver: local

networks:
  frontend:
    external: true

services:
  traefik:
    env_file:
      - ./.env
    environment:
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf-token
    image: traefik:latest
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    secrets:
      - cf-token
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik-${HOSTNAME}.interactivebackdraft.com`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik-${HOSTNAME}.interactivebackdraft.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=production"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=interactivebackdraft.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.interactivebackdraft.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"
    ports: 
    - 80:80
    - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - traefik-data:/etc/traefik/certs/
    restart: unless-stopped
    networks:
      - frontend
      
