volumes:
  portainer-data:
      driver: local
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.20.3
    ports:
      - 9000:9000
      - 9443:9443
      - 8000:8000
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: unless-stopped


