volumes:
  portainer-data:
      driver: local
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.33.0
    ports:
      - 8000:8000
    volumes:
      - /run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=web, websecure
      - traefik.http.routers.portainer.rule=Host(`portainer.local.interactivebackdraft.com`)
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=production
      - traefik.http.services.portainer.loadbalancer.server.port=9000

networks:
  frontend:
    external: true


